export {
  type Actor,
  ActorSchema,
  activeJournalEntries,
  appendEntry,
  type CreateJournalEntryOptions,
  canRedoJournal,
  canUndoJournal,
  clear,
  commitStatus,
  createJournal,
  createJournalEntry,
  type ElementSnapshot,
  ElementSnapshotSchema,
  type EvidenceRef,
  EvidenceRefSchema,
  type Journal,
  type JournalEntry,
  JournalEntrySchema,
  type JournalEntryStatus,
  JournalEntryStatusSchema,
  JournalSchema,
  markEntryCommitted,
  markEntryReverted,
  markEntrySuperseded,
  peekRedo,
  peekUndo,
  type RedoOutcome,
  type RuntimeAssertion,
  RuntimeAssertionSchema,
  redo,
  StaleInverseError,
  type UndoOutcome,
  UndoRedoStacksSchema,
  undo,
} from "./journal.js";

export { migrateJournal_v1_to_v2, migrateJournalEntry_v1_to_v2 } from "./migration.js";

export {
  deserializeJournal,
  type ParseError,
  type ParseResult,
  serializeJournal,
} from "./persistence.js";

export {
  canRedo,
  canUndo,
  createStacks,
  pushAppliedClearingRedo,
  type TransferResult,
  transferRedoToUndo,
  transferUndoToRedo,
  type UndoRedoStacks,
} from "./stacks.js";
